### ISSUE TITLE
카카오 API 로그인, 페이지 샘플 제작

### ISSUE THREAD

**Issue by reddresseson** [hebal400/lookingforalba#2]
1월 13일 일요일까지

**Comment by aerain** [comment]
# 카카오 로그인 진행상황 @reddresseson @yunjipark0623 @niceaji 
## 진행 보고
1. 크롬 확장 내부에서 외부 js injection 불가

CSP(Content Security Policy) 관련 이슈로 외부 자바스크립트의 실행의 문제가 있었습니다. 이를 해결하기 위해 manifest.json에 다음 구문을 추가함으로써 해결하였습니다.

```
{
...
"content_security_policy": "script-src 'self' https://developers.kakao.com; object-src 'self'",
...
}
```
2. kakao.js should be loaded from a web server

크롬 확장은 서버 방식으로 동작하는 방식이 아니라 filesystem 내에서 동작하기 때문에 JavaScript SDK를 사용할 수 없었습니다. 때문에 Rest API를 통한 인증 방식을 시도하였습니다.

3. 웹 도메인 필요

오로지 SDK의 동작만 보다가 제일 필수로 봐야 하는 사용자 관리의 필수 사항을 놓쳤습니다. 사용자 관리를 위해서는 관리를 위한 도메인과 redirect_url을 요구하였습니다. 기존에 저희가 생각했던 chrome extension 내부에서 동작하는 인증은 사용할 수 없었습니다. 

---

## 개발 방향 수정의 필요성.

초기 개발 사항에서 우리 팀원들은 chrome extension 내에서 모든 것을 만들 수 있다고 생각했지만. 사용자 관리 API 를 통해서 웹 서버는 반드시 필요하다고 판단하였습니다. 이를 해결하기 위해 다음과 같은 개발 방식이 필요합니다.
- 크롬 확장 내부에서 iframe 태그를 통한 웹 서버로 동작하는 외부 html 로드
- 저희가 고려했던 게시글 공유, 사용자 인증 등의 기능은 외부 html 에서 개발해야만 합니다.

**Comment by aerain** [comment]
hebal400.github.io 를 통해 구현하였습니다.
