### ISSUE TITLE
알바 급여 계산기 디자인, SPA 공부

### ISSUE THREAD

**Issue by reddresseson** [hebal400/lookingforalba#4]
1월 13일 까지

**Comment by reddresseson** [comment]
https://ovenapp.io/view/bAip9eMMOWx9ea1YoIQHwaZnHBjSh11E/
oven으로 만든 프로토타입입니다.

**Comment by niceaji** [comment]
@reddresseson 근데 급여계산기도 확장에 들어가는건가요?

**Comment by niceaji** [comment]
@reddresseson  https://github.com/hebal400/lookingforalba/wiki/%ED%9A%8C%EC%9D%98-%EA%B2%B0%EA%B3%BC 아 그러네요 ^^
