### ISSUE TITLE
여러가지 도움주기 

### ISSUE THREAD

**Issue by niceaji** [hebal400/lookingforalba#5]

**Comment by niceaji** [comment]
@aerain @reddresseson @yunjipark0623 드디어 미션이 결정이 되었군요. 축하 👍 
크롬확장은 JS로 개발되기에 그대로 소스도 볼수 있어요. 
비슷한 기능이 크롬확장을 리뷰해서 소스를 보고 참고하면 금방 만들수 있을듯 합니다.

- https://developer.chrome.com/extensions
- http://reddreams.tistory.com/1099

**Comment by niceaji** [comment]
@aerain @reddresseson @yunjipark0623 
http://www.mapcrunch.com/ 랜덤 스트리트뷰 . 이런서비스도 재밌네요

**Comment by aerain** [comment]
스트리트만 되는줄 알았더니 이런 해변가도 되네요 ~~
