### ISSUE TITLE
웹 파싱, url redirection

### ISSUE THREAD

**Issue by reddresseson** [hebal400/lookingforalba#8]
21일 월요일까지

**Comment by aerain** [comment]
알바천국 웹 파싱 구현 완료

**Comment by niceaji** [comment]
@aerain 소스는 어디있나요?

**Comment by aerain** [comment]
데이터 따는 부분은 lookingforalba 레포의 parse.js 안에 있습니다!

**Comment by aerain** [comment]
url 리다이렉션을 albatalk 레포지토리에 redirect.html과 redirect.js 로 테스트로 만들었습니다.
GET 방식으로 redirect_uri에 주소를 넣어 해당 사이트로 리다이렉션을 할수 있게 테스트하였습니다.

현재는 주소 유효성 체크등의 이유로 실행 안되게 만들어놓았습니다.

**Comment by niceaji** [comment]
https://github.com/hebal400/lookingforalba/blob/master/parse.js

**Comment by aerain** [comment]
알바몬 파싱 추가하였습니다.
파일 이름이 변경되어 다시 링크 추가 합니다.

## 알바천국
[https://github.com/hebal400/lookingforalba/blob/master/albaparse.js](url)

## 알바몬
[https://github.com/hebal400/lookingforalba/blob/master/albamonparse.js](url)
